INSERT INTO juego (pregunta, respuesta1, respuesta2, respuesta3, respuesta4, respuesta_correcta) VALUES
('¿Cómo se llama el hobbit que porta el Anillo Único?', 'Bilbo', 'Frodo', 'Sam', 'Merry', 2),
('¿Quién forjó el Anillo Único?', 'Saruman', 'Sauron', 'Celebrimbor', 'Melkor', 2),
('¿Cómo se llama la espada que Aragorn porta reforjada?', 'Glamdring', 'Orcrist', 'Andúril', 'Narsil', 3),
('¿Qué criatura es Gollum originalmente?', 'Elfo', 'Hobbit', 'Enano', 'Hombre', 2),
('¿Cómo se llama el mago gris?', 'Radagast', 'Saruman', 'Gandalf', 'Alatar', 3),
('¿Qué reino gobierna Aragorn?', 'Rohan', 'Gondor', 'Mordor', 'Dale', 2),
('¿Quién mata al Rey Brujo de Angmar?', 'Aragorn', 'Frodo', 'Éowyn', 'Legolas', 3),
('¿Cómo se llama el bosque donde viven los ents?', 'Fangorn', 'Lothlórien', 'Mirkwood', 'Bree', 1),
('¿Quién es el padre de Legolas?', 'Thranduil', 'Elrond', 'Denethor', 'Glóin', 1),
('¿Qué criatura guía a Frodo hacia Mordor?', 'Sméagol', 'Azog', 'Bolg', 'Shelob', 1),
('¿Cómo se llama la araña gigante?', 'Ungoliant', 'Shelob', 'Aragog', 'Nessa', 2),
('¿Dónde se destruye el Anillo?', 'Monte Gundabad', 'Monte del Destino', 'Erebor', 'Orodruin', 2),
('¿Quién lidera a los Uruk-hai en la primera película?', 'Azog', 'Lurtz', 'Gothmog', 'Grishnákh', 2),
('¿Cuál es la capital de Rohan?', 'Edoras', 'Minas Tirith', 'Helm', 'Isengard', 1),
('¿Quién es el mayordomo de Gondor?', 'Boromir', 'Denethor', 'Faramir', 'Théoden', 2),
('¿Cómo se llama el hijo de Denethor?', 'Faramir', 'Éomer', 'Balin', 'Théodred', 1),
('¿Qué objeto ilumina cuando hay orcos cerca?', 'El Anillo', 'Sting/Dardo', 'Palantír', 'Andúril', 2),
('¿Quién acompaña siempre a Frodo?', 'Pippin', 'Sam', 'Merry', 'Gimli', 2),
('¿Qué pueblo habita la Comarca?', 'Elfos', 'Hobbits', 'Hombres', 'Enanos', 2),
('¿Cómo se llama el caballo de Gandalf?', 'Hasufel', 'Arod', 'Sombragrís', 'Brego', 3),
('¿Quién rompe el bastón de Saruman?', 'Elrond', 'Galadriel', 'Gandalf', 'Aragorn', 3),
('¿Dónde vive Galadriel?', 'Rivendel', 'Lothlórien', 'Isengard', 'Moria', 2),
('¿Qué mina atraviesa la Comunidad?', 'Erebor', 'Moria', 'Nogrod', 'Khazad', 2),
('¿Qué demonio antiguo aparece en Moria?', 'Dragón', 'Balrog', 'Nazgûl', 'Kraken', 2),
('¿Cuántos miembros forman la Comunidad del Anillo?', '7', '8', '9', '10', 3),
('¿Quién hereda el Anillo de Bilbo?', 'Sam', 'Frodo', 'Pippin', 'Rosie', 2),
('¿Qué torre es el ojo de Sauron?', 'Barad-dûr', 'Orthanc', 'Minas Morgul', 'Cirith Ungol', 1),
('¿Quién dice "No puedes pasar"?', 'Aragorn', 'Gandalf', 'Boromir', 'Elrond', 2),
('¿Qué regalo da Galadriel a Frodo?', 'Una capa', 'La luz de Eärendil', 'Una espada', 'Un anillo', 2),
('¿Quién intenta quitarle el Anillo a Frodo?', 'Faramir', 'Boromir', 'Théoden', 'Legolas', 2);
